pipeline:
  name: Build MERN-Stack-Example
  identifier: Build_MERN_Stack_Example_1718095256290
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: installing dependance
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: |-
                      cd server
                      yarn install;
                      yarn test;
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: ygreddy/ubuntu
                    tags:
                      - latest
                    dockerfile: server/Dockerfile
                    context: server
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: githubharnes
        repoName: MERN-Stack-Example
        build: <+input>
